version: '3.8'

volumes: 
  database_volume_dev:

services: 
  frontend_dev:
    container_name: frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports: 
      - 3000:3000
    environment: 
      - CHOKIDAR_USEPOLLING=true

  backend_dev:
    container_name: backend_dev
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - ./backend/:/usr/src/app/
    env_file: 
      - ./.dev.env
    ports: 
      - 8000:8000
    depends_on: 
      - database_dev
    command: python manage.py runserver 0.0.0.0:8000
  
  database_dev:
    container_name: database_dev
    image: postgis/postgis:latest
    volumes: 
      - database_volume_dev:/var/lib/postgresql/data
    env_file: 
      - ./.dev.env
    ports: 
      - 5432:5432