version: '3.8'

volumes: 
  database_volume_prod:
  static_volume_prod:
  media_volume_prod:

services: 
  nginx:
    build: ./nginx
    volumes:
      - static_volume_prod:/home/birdie/web/static
      - media_volume_prod:/home/birdie/web/media 
    ports:
      - 9000:80
    depends_on: 
      - backend_prod

  backend_prod:
    container_name: backend_prod
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume_prod:/home/birdie/web/static
      - media_volume_prod:/home/birdie/web/media
    env_file: 
      - ./.prod.env
    expose: 
      - 8000
    depends_on: 
      - database_prod
    command: gunicorn birdie.wsgi:application --bind 0.0.0.0:8000
  
  database_prod:
    container_name: database_prod
    image: postgis/postgis:latest
    volumes: 
      - database_volume_prod:/var/lib/postgresql/data
    env_file: 
      - ./.prod.db.env