# Generated by Django 3.1.1 on 2020-11-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200929_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(upload_to='file_storage/profile_pictures'),
        ),
    ]
