# Generated by Django 3.1.1 on 2020-10-01 12:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200929_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Price_bracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название ресторана.', max_length=20)),
                ('description', models.CharField(help_text='Описание ресторана.', max_length=1000)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('card_picture', models.ImageField(blank=True, null=True, upload_to='file_storage/restrant_card_picture')),
                ('food_type', models.ManyToManyField(to='backend.Food_type')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='file_storage/profile_pictures'),
        ),
        migrations.CreateModel(
            name='Restaurant_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='file_storage/restaurant_pictures')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Food_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='file_storage/food_pictures')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurant')),
            ],
        ),
    ]
