# Generated by Django 3.1.1 on 2020-10-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201001_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food_type',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='price_bracket',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name']},
        ),
    ]
