# Generated by Django 3.1.1 on 2020-10-02 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201001_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('news_text', models.CharField(max_length=1000)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('card_picture', models.ImageField(blank=True, null=True, upload_to='file_storage/news_picture_card')),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
        migrations.AlterField(
            model_name='food_picture',
            name='picture',
            field=models.ImageField(upload_to='file_storage/food_pictures'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('down_voite_users', models.ManyToManyField(related_name='down_voite_users', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurant')),
                ('up_voite_users', models.ManyToManyField(related_name='up_voite_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
        migrations.CreateModel(
            name='News_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='file_storage/news_pictures')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.news')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
