# Generated by Django 3.1.1 on 2020-10-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201002_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend.news_type'),
            preserve_default=False,
        ),
    ]
