# Generated by Django 3.1.1 on 2020-10-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201004_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(help_text='Описание ресторана.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
