# Generated by Django 3.1.1 on 2020-10-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201004_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01 00:00'),
            preserve_default=False,
        ),
    ]
