# Generated by Django 3.1.1 on 2020-10-04 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20201004_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='price_bracket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='backend.price_bracket'),
            preserve_default=False,
        ),
    ]
