# Generated by Django 3.1.1 on 2020-10-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_restaurant_price_bracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_useful',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
