# Generated by Django 3.1.1 on 2020-10-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20201009_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food_type',
            options={'ordering': ['name'], 'verbose_name': 'Тип еды', 'verbose_name_plural': 'Типы еды'},
        ),
        migrations.AlterModelOptions(
            name='news_type',
            options={'verbose_name': 'Тип новости', 'verbose_name_plural': 'Типы ресторанов'},
        ),
        migrations.AlterModelOptions(
            name='price_bracket',
            options={'ordering': ['name'], 'verbose_name': 'Ценовая категория', 'verbose_name_plural': 'Ценовые категории'},
        ),
        migrations.AlterField(
            model_name='food_picture',
            name='picture',
            field=models.FileField(upload_to='file_storage/food_pictures'),
        ),
        migrations.AlterField(
            model_name='news',
            name='card_picture',
            field=models.FileField(blank=True, null=True, upload_to='file_storage/news_picture_card'),
        ),
        migrations.AlterField(
            model_name='news_picture',
            name='picture',
            field=models.FileField(upload_to='file_storage/news_pictures'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='card_picture',
            field=models.FileField(blank=True, null=True, upload_to='file_storage/restrant_card_picture'),
        ),
        migrations.AlterField(
            model_name='restaurant_picture',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='file_storage/restaurant_pictures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='file_storage/profile_pictures'),
        ),
    ]
