# Generated by Django 3.1.1 on 2020-10-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_restaurant_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
    ]
