# Generated by Django 3.1.1 on 2020-10-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_restaurant_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_useful',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
