# Generated by Django 3.1.1 on 2020-11-06 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20201011_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='file_storage/restaurant_pictures')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurant')),
            ],
        ),
        migrations.RenameModel(
            old_name='Food_picture',
            new_name='FoodPicture',
        ),
        migrations.RenameModel(
            old_name='Food_type',
            new_name='FoodType',
        ),
        migrations.RenameModel(
            old_name='News_picture',
            new_name='NewsPicture',
        ),
        migrations.RenameModel(
            old_name='News_type',
            new_name='NewsType',
        ),
        migrations.RenameModel(
            old_name='Price_bracket',
            new_name='PriceBracket',
        ),
        migrations.RenameModel(
            old_name='Restaurant_rating',
            new_name='RestaurantRating',
        ),
        migrations.DeleteModel(
            name='Restaurant_picture',
        ),
    ]
