# Generated by Django 3.1.1 on 2020-11-07 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20201106_2100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstype',
            options={'verbose_name': 'Тип новости', 'verbose_name_plural': 'Типы новостей'},
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_bracket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_bracket', to='backend.pricebracket'),
        ),
        migrations.AlterField(
            model_name='restaurantrating',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_rt', to='backend.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantrating',
            unique_together={('restaurant', 'user')},
        ),
    ]
