# Generated by Django 3.1.1 on 2020-11-08 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20201108_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpicture',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='backend.restaurant'),
        ),
    ]
