# Generated by Django 3.1.1 on 2020-11-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpicture',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_pictures', to='backend.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurantpicture',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_pictures', to='backend.restaurant'),
        ),
    ]
