# Generated by Django 3.1.1 on 2020-11-23 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='down_voite_users',
        ),
        migrations.RemoveField(
            model_name='review',
            name='up_voite_users',
        ),
        migrations.AddField(
            model_name='review',
            name='down_vote_users',
            field=models.ManyToManyField(blank=True, related_name='down_voite_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='up_vote_users',
            field=models.ManyToManyField(blank=True, related_name='up_voite_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
